name: Playwright Tests 2
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: | 
        pytest cookiecutters.py
    - name: Run your tests
      run: python --tracing=retain-on-failure mycookieclicker.py
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: trace.zip
        path: . 
